const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'./images/p1.jpg',
            price:46,
            brand:'Nike',
            rating:5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'2',
            name:'Adidas Slim Shirt',
            category:'Shirts',
            image:'./images/p2.jpg',
            price:33,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'3',
            name:'Lacoste Slim Shirt',
            category:'Shirts',
            image:'./images/p3.jpg',
            price:40,
            brand:'Lacoste',
            rating:4.5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pants',
            category:'Pants',
            image:'./images/p4.jpg',
            price:55,
            brand:'Nike',
            rating:3,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'5',
            name:'Adidas Slim Pants',
            category:'Pants',
            image:'./images/p5.jpg',
            price:87,
            brand:'Adidas',
            rating:4,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'6',
            name:'Lacoste Slim Pants',
            category:'Pants',
            image:'./images/p6.jpg',
            price:70,
            brand:'Lacoste',
            rating:4.5,
            numReviews:10,
            description:'High quality product',
        },
    ]
}

export default data;